### PR TITLE
Feedback if config.json already exists

### PR DESCRIPTION
**Pull request by mccalluc**
Not sure if the logic is quite right, and would it be possible for it to fail fast? Towards #909 or #2218?

### CODE REVIEW

**Comment by hackdna** [comment]
Do we all agree that we want to change the current behavior to backup and replace existing`config.json` with a new version? If yes, then it is a lot easier to do using the [backup attribute of the file resource](https://docs.puppet.com/puppet/3/type.html#file-attribute-backup).

**Comment by drj11** [comment]
replacing is fine for AWS (preferred, strongly).

Would vagrant users be upset? I thought they might have existing modifications in their `config.json` that they don't want overwritten.

**Comment by hackdna** [comment]
We do immutable deployments on AWS, so config.json is always created from scratch there.

I never actually customize my local config.json. I did run into problems when new settings were introduced, so I think overwriting it on updates would be a good idea (if it's backed up first).

**Comment by mccalluc** [comment]
Ok, so I'll close this, but added a comment to #909 referencing `file-attribute-backup`.

**Pull request closed without merging**
