### PR TITLE
Jkmarx/add modal tool launch error

### LINKED ISSUE #2113: Meaningful error in UI when container count limit is hit
Right now, in the console I see angular errors: It's getting a 400, with the data "Max containers".

### LINKED ISSUE #2204: If files have not completely downloaded, visualizations fail silently.
* Specific code commit: e6a306129da75e6ebfeab875b655ca3d50b1659f 
* Version of the web browser and OS: FF MacOS
* Environment where the error occurred: local dev 

### Steps to reproduce
Please list all the actions and the input data used:

1. Import a CSV, but do not actually upload any of the local files it references
2. Go to the file browser, select a visualization (or a workflow) an choose one of the lines with a lightning bolt as input.

### Observed behavior
It tries to POST to http://192.168.50.50:8000/api/v2/tools/:
```
dataset_uuid | 1c27278f-6123-47e9-96b2-45e4f0b6678e
tool_definition_uuid | 74421010-8f15-4b01-8d74-5ecb8f4c806f
file_relationships | [476ec692-1a28-44e7-b03c-3bc0c830df27]
parameters | Object
```
but the response is `Node with uuid: 476ec692-1a28-44e7-b03c-3bc0c830df27 has no associated file url`.

### Expected behavior
Either:
- (a) entries with lighting-bolt should not be selectable (no arrow at the left)
- or (b) there should be an error the user can see explaining why nothing is happening.

Was leaning towards (a), but Scott pointed out that if these were remote files, it wouldn't necessarily be a problem: There would be a valid url, even if the status was a lightning bolt.

Scott points out that #2113 is probably the same issue: We need a UI exposure when API requests fail.

### LINKED ISSUE #2211: If a Tool launch fails, it fails silently
When Launching a Tool from FileBrowser 2 fails, it yields a proper HTTP error response but there is no ui element to display this error to the end user.

I expect that we could capture this info and display in a modal or something of the like.

Related to:
#2113 
#2204

### PR DESCRIPTION
**Pull request by jkmarx**
- Resolves #2211 
- Add generic Error API

Also:
resolves #2113 [Scott]
resolves #2204 [Scott]

### CODE REVIEW

**Comment by jkmarx** [comment]
screen shot 2017-10-20 at 1 20 10 pm

screen shot 2017-10-20 at 1 20 42 pm
screen shot 2017-10-20 at 1 21 37 pm
screen shot 2017-10-20 at 1 22 52 pm

-- Standard bootstrap Modal -- 
screen shot 2017-10-20 at 11 58 20 am

**Comment by jkmarx** [comment]
@scottx611x Comments on the text?
screen shot 2017-10-23 at 7 14 22 am

**Comment by mccalluc** [comment]
Not sure where this is in the code, but 
> Unable to launch tool, please try again.
is a comma splice: Change to period, colon, or semi-colon.

Otherwise looks great.

**Comment by jkmarx** [comment]
Oops, I'd already updated the text. Wrong image. @mccalluc @scottx611x 
screen shot 2017-10-23 at 7 27 56 am

**Comment by mccalluc** [comment]
great!

**Pull request merged**
