### PR TITLE
Switch network adapter type to paravirtualized for increased performance

### PR DESCRIPTION
**Pull request by hackdna**
Increase guest OS network performance by ~100x for faster S3 transfers and provisioning

### CODE REVIEW

**Comment by hackdna** [comment]
We do now.

**Comment by scottx611x** [comment]
@hackdna Oh, okay I wasn't aware. 

So someone couldn't properly develop locally if their network connection went down? 
Does one have to run terraform commands after provisioning a vagrant box?

**Comment by hackdna** [comment]
Well, it's not really possible to develop "locally" anymore because a lot of tests require an Internet connection.

Regardless, the file storage backend can be specified using [DEFAULT_FILE_STORAGE Django setting](https://docs.djangoproject.com/en/1.8/ref/settings/#default-file-storage). Default is `SymlinkedFileSystemStorage` (derived from `django.core.files.storage.FileSystemStorage`) in Vagrant and it does not require an Internet connection.

The only requirement to enable the new functionality in this PR is to run `vagrant reload`.

**Comment by scottx611x** [comment]
Okay sure, I think I was more confused about your comment here: https://github.com/refinery-platform/refinery-platform/pull/2748#issuecomment-387503096... But you're just switching the storage backend to S3Storage to do some file_store specific testing, correct? It's not something we normally do, but something we can do if necessary. 

Do you think it would be useful to have some notes on how one could configure their Vagrant instance to be able to talk to s3? Its a little more involved than switching the storage backend, no?

Why not just bring up an AWS stack to test such functionality?

**Comment by hackdna** [comment]
The change in this PR is completely backward-compatible and does not require any configuration or updates. Once S3 storage backend support is fully functional it will also have all the necessary documentation.

**Comment by hackdna** [comment]
Happy to discuss this in depth at the next dev meeting.

**Pull request merged**
