### PR TITLE
Scottx611x/selenium bug fix

### PR DESCRIPTION
**Pull request by scottx611x**
Addresses Errors like: `OSError=[Errno 12] Cannot allocate memory` when running selenium-based tests locally which occurred due to: https://github.com/mozilla/geckodriver/issues/613

### CODE REVIEW

**Comment by raghavilatha** [comment]
I am getting the same error still, Could you help me out how can I solve this issue ?

**Comment by scottx611x** [comment]
@raghavilatha Could you try running: `ps -aux | grep Xvfb` in your vm?
If that yields any stale Xvfb processes hanging around then a `sudo killall Xvfb` should do the trick to free up your mem. Let me know how that works!

**Comment by raghavilatha** [comment]
Thankyou so mucv Scott611x.
I will try and let you know.

Thanks,
Raghavi.

**Comment by raghavilatha** [comment]
I am not knowing how to run this command in windows pc.  Could you help me
out?

**Comment by scottx611x** [comment]
Hi @raghavilatha You will need to run these commands inside of your vagrant vm. 

So, after running a `vagrant ssh`.

Also curious as to the command you ran to receive the `OSError=[Errno 12] Cannot allocate memory` if you could provide me with that.

**Comment by raghavilatha** [comment]
@scottx611x 

I am facing this below issue.

1500658889294	geckodriver	INFO	geckodriver 0.18.0
1500658889307	geckodriver	INFO	Listening on 127.0.0.1:4610
1500658896760	geckodriver::marionette	INFO	Starting browser C:\Program Files (x86)\Mozilla Firefox\firefox.exe with args ["-marionette"]
1500658897269	addons.manager	DEBUG	Application has been upgraded
1500658897334	addons.manager	DEBUG	Loaded provider scope for resource://gre/modules/addons/XPIProvider.jsm: ["XPIProvider"]
1500658897337	addons.manager	DEBUG	Loaded provider scope for resource://gre/modules/LightweightThemeManager.jsm: ["LightweightThemeManager"]
1500658897342	addons.manager	DEBUG	Loaded provider scope for resource://gre/modules/addons/GMPProvider.jsm
1500658897345	addons.manager	DEBUG	Loaded provider scope for resource://gre/modules/addons/PluginProvider.jsm
1500658897346	addons.manager	DEBUG	Starting provider: XPIProvider
1500658897346	addons.xpi	DEBUG	startup
1500658897347	addons.xpi	INFO	Removing all system add-on upgrades.
1500658897347	addons.xpi	INFO	SystemAddonInstallLocation directory is missing
1500658897348	addons.xpi	INFO	Mapping aushelper@mozilla.org to C:\Program Files (x86)\Mozilla Firefox\browser\features\aushelper@mozilla.org.xpi
1500658897349	addons.xpi	INFO	Mapping e10srollout@mozilla.org to C:\Program Files (x86)\Mozilla Firefox\browser\features\e10srollout@mozilla.org.xpi
1500658897349	addons.xpi	INFO	Mapping firefox@getpocket.com to C:\Program Files (x86)\Mozilla Firefox\browser\features\firefox@getpocket.com.xpi
1500658897350	addons.xpi	INFO	Mapping screenshots@mozilla.org to C:\Program Files (x86)\Mozilla Firefox\browser\features\screenshots@mozilla.org.xpi
1500658897350	addons.xpi	INFO	Mapping webcompat@mozilla.org to C:\Program Files (x86)\Mozilla Firefox\browser\features\webcompat@mozilla.org.xpi
1500658897351	addons.xpi	INFO	Mapping {972ce4c6-7e08-4474-a285-3208198ce6fd} to C:\Program Files (x86)\Mozilla Firefox\browser\extensions\{972ce4c6-7e08-4474-a285-3208198ce6fd}.xpi
1500658897352	addons.xpi	DEBUG	checkForChanges
1500658897352	addons.xpi	INFO	SystemAddonInstallLocation directory is missing
1500658897353	addons.xpi	DEBUG	Loaded add-on state from prefs: {"app-system-defaults":{"aushelper@mozilla.org":{"d":"C:\\Program Files (x86)\\Mozilla Firefox\\browser\\features\\aushelper@mozilla.org.xpi","e":true,"v":"2.0","st":1495096108000},"e10srollout@mozilla.org":{"d":"C:\\Program Files (x86)\\Mozilla Firefox\\browser\\features\\e10srollout@mozilla.org.xpi","e":true,"v":"1.14","st":1495096108000},"firefox@getpocket.com":{"d":"C:\\Program Files (x86)\\Mozilla Firefox\\browser\\features\\firefox@getpocket.com.xpi","e":true,"v":"1.0.5","st":1495096109000},"webcompat@mozilla.org":{"d":"C:\\Program Files (x86)\\Mozilla Firefox\\browser\\features\\webcompat@mozilla.org.xpi","e":true,"v":"1.0","st":1495096108000}},"app-global":{"{972ce4c6-7e08-4474-a285-3208198ce6fd}":{"d":"C:\\Program Files (x86)\\Mozilla Firefox\\browser\\extensions\\{972ce4c6-7e08-4474-a285-3208198ce6fd}.xpi","e":true,"v":"53.0.3","st":1495096108000}}}
1500658897356	addons.xpi	DEBUG	getModTime: Recursive scan of aushelper@mozilla.org
1500658897359	addons.xpi	DEBUG	Changed add-on aushelper@mozilla.org in app-system-defaults
1500658897360	addons.xpi	DEBUG	getModTime: Recursive scan of e10srollout@mozilla.org
1500658897361	addons.xpi	DEBUG	Changed add-on e10srollout@mozilla.org in app-system-defaults
1500658897362	addons.xpi	DEBUG	getModTime: Recursive scan of firefox@getpocket.com
1500658897362	addons.xpi	DEBUG	Changed add-on firefox@getpocket.com in app-system-defaults
1500658897363	addons.xpi	DEBUG	New add-on screenshots@mozilla.org in app-system-defaults
1500658897363	addons.xpi	DEBUG	getModTime: Recursive scan of screenshots@mozilla.org
1500658897364	addons.xpi	DEBUG	getModTime: Recursive scan of webcompat@mozilla.org
1500658897365	addons.xpi	DEBUG	Changed add-on webcompat@mozilla.org in app-system-defaults
1500658897366	addons.xpi	DEBUG	getModTime: Recursive scan of {972ce4c6-7e08-4474-a285-3208198ce6fd}
1500658897366	addons.xpi	DEBUG	Changed add-on {972ce4c6-7e08-4474-a285-3208198ce6fd} in app-global
1500658897367	addons.xpi	DEBUG	getInstallState changed: true, state: {"app-system-defaults":{"aushelper@mozilla.org":{"d":"C:\\Program Files (x86)\\Mozilla Firefox\\browser\\features\\aushelper@mozilla.org.xpi","e":true,"v":"2.0","st":1500601813818},"e10srollout@mozilla.org":{"d":"C:\\Program Files (x86)\\Mozilla Firefox\\browser\\features\\e10srollout@mozilla.org.xpi","e":true,"v":"1.14","st":1500601813818},"firefox@getpocket.com":{"d":"C:\\Program Files (x86)\\Mozilla Firefox\\browser\\features\\firefox@getpocket.com.xpi","e":true,"v":"1.0.5","st":1500601813802},"screenshots@mozilla.org":{"d":"C:\\Program Files (x86)\\Mozilla Firefox\\browser\\features\\screenshots@mozilla.org.xpi","st":1500601813911},"webcompat@mozilla.org":{"d":"C:\\Program Files (x86)\\Mozilla Firefox\\browser\\features\\webcompat@mozilla.org.xpi","e":true,"v":"1.0","st":1500601813786}},"app-global":{"{972ce4c6-7e08-4474-a285-3208198ce6fd}":{"d":"C:\\Program Files (x86)\\Mozilla Firefox\\browser\\extensions\\{972ce4c6-7e08-4474-a285-3208198ce6fd}.xpi","e":true,"v":"53.0.3","st":1500601813833}}}
1500658897379	addons.xpi-utils	DEBUG	Opening XPI database C:\Users\M1040326\AppData\Local\Temp\rust_mozprofile.k0GA8zViHeBF\extensions.json
1500658897382	addons.xpi-utils	DEBUG	Successfully read XPI database
1500658897385	addons.xpi-utils	DEBUG	Add-on e10srollout@mozilla.org modified in app-system-defaults
*** Blocklist::_loadBlocklistFromFile: blocklist is disabled
1500658897410	DeferredSave.extensions.json	DEBUG	Save changes
1500658897413	DeferredSave.extensions.json	DEBUG	Save changes
1500658897413	addons.xpi-utils	DEBUG	Add-on firefox@getpocket.com modified in app-system-defaults
1500658897434	DeferredSave.extensions.json	DEBUG	Starting timer
1500658897445	DeferredSave.extensions.json	DEBUG	Save changes
1500658897446	DeferredSave.extensions.json	DEBUG	Save changes
1500658897446	addons.xpi-utils	DEBUG	Add-on aushelper@mozilla.org modified in app-system-defaults
1500658897458	DeferredSave.extensions.json	DEBUG	Save changes
1500658897459	DeferredSave.extensions.json	DEBUG	Save changes
1500658897459	addons.xpi-utils	DEBUG	Add-on webcompat@mozilla.org modified in app-system-defaults
1500658897464	DeferredSave.extensions.json	DEBUG	Save changes
1500658897465	DeferredSave.extensions.json	DEBUG	Save changes
1500658897465	addons.xpi-utils	DEBUG	New add-on screenshots@mozilla.org installed in app-system-defaults
1500658897486	DeferredSave.extensions.json	DEBUG	Save changes
1500658897486	addons.xpi-utils	DEBUG	Add-on {972ce4c6-7e08-4474-a285-3208198ce6fd} modified in app-global
1500658897498	DeferredSave.extensions.json	DEBUG	Save changes
1500658897501	DeferredSave.extensions.json	DEBUG	Save changes
1500658897502	addons.manager	DEBUG	Registering startup change 'changed' for e10srollout@mozilla.org
1500658897525	addons.xpi	DEBUG	Loading bootstrap scope from C:\Program Files (x86)\Mozilla Firefox\browser\features\e10srollout@mozilla.org.xpi
1500658897533	addons.xpi	DEBUG	Calling bootstrap method install on e10srollout@mozilla.org version 1.50
1500658897534	addons.xpi-utils	DEBUG	Make addon app-system-defaults:e10srollout@mozilla.org visible
1500658897535	DeferredSave.extensions.json	DEBUG	Save changes
1500658897535	addons.manager	DEBUG	Registering startup change 'changed' for firefox@getpocket.com
1500658897536	addons.xpi	DEBUG	Loading bootstrap scope from C:\Program Files (x86)\Mozilla Firefox\browser\features\firefox@getpocket.com.xpi
1500658897543	addons.xpi	DEBUG	Calling bootstrap method install on firefox@getpocket.com version 1.0.5
1500658897543	addons.xpi-utils	DEBUG	Make addon app-system-defaults:firefox@getpocket.com visible
1500658897544	DeferredSave.extensions.json	DEBUG	Save changes
1500658897544	addons.manager	DEBUG	Registering startup change 'changed' for aushelper@mozilla.org
1500658897545	addons.xpi	DEBUG	Loading bootstrap scope from C:\Program Files (x86)\Mozilla Firefox\browser\features\aushelper@mozilla.org.xpi
1500658897551	addons.xpi	DEBUG	Calling bootstrap method install on aushelper@mozilla.org version 2.0
1500658897552	addons.xpi-utils	DEBUG	Make addon app-system-defaults:aushelper@mozilla.org visible
1500658897552	DeferredSave.extensions.json	DEBUG	Save changes
1500658897552	addons.manager	DEBUG	Registering startup change 'changed' for webcompat@mozilla.org
1500658897554	addons.xpi	DEBUG	Loading bootstrap scope from C:\Program Files (x86)\Mozilla Firefox\browser\features\webcompat@mozilla.org.xpi
1500658897559	addons.xpi	DEBUG	Calling bootstrap method install on webcompat@mozilla.org version 1.1
1500658897559	addons.xpi-utils	DEBUG	Make addon app-system-defaults:webcompat@mozilla.org visible
1500658897559	DeferredSave.extensions.json	DEBUG	Save changes
1500658897560	addons.manager	DEBUG	Registering startup change 'installed' for screenshots@mozilla.org
1500658897561	addons.xpi	DEBUG	Loading bootstrap scope from C:\Program Files (x86)\Mozilla Firefox\browser\features\screenshots@mozilla.org.xpi
1500658897566	addons.xpi	DEBUG	Calling bootstrap method install on screenshots@mozilla.org version 6.6.0
1500658897567	addons.xpi-utils	DEBUG	Make addon app-system-defaults:screenshots@mozilla.org visible
1500658897567	DeferredSave.extensions.json	DEBUG	Save changes
1500658897567	addons.manager	DEBUG	Registering startup change 'changed' for {972ce4c6-7e08-4474-a285-3208198ce6fd}
1500658897568	addons.xpi-utils	DEBUG	Make addon app-global:{972ce4c6-7e08-4474-a285-3208198ce6fd} visible
1500658897568	DeferredSave.extensions.json	DEBUG	Save changes
1500658897569	addons.xpi	DEBUG	Updating XPIState for {"id":"e10srollout@mozilla.org","syncGUID":"{43bfc1f5-95ea-4e77-aaaa-598f3dd0b56d}","location":"app-system-defaults","version":"1.50","type":"extension","internalName":null,"updateURL":null,"updateKey":null,"optionsURL":null,"optionsType":null,"aboutURL":null,"icons":{},"iconURL":null,"icon64URL":null,"defaultLocale":{"name":"Multi-process staged rollout","description":"Staged rollout of Firefox multi-process feature.","creator":null,"homepageURL":null},"visible":true,"active":true,"userDisabled":false,"appDisabled":false,"descriptor":"C:\\Program Files (x86)\\Mozilla Firefox\\browser\\features\\e10srollout@mozilla.org.xpi","installDate":1495096108000,"updateDate":1500601813818,"applyBackgroundUpdates":1,"bootstrap":true,"skinnable":false,"size":12519,"sourceURI":null,"releaseNotesURI":null,"softDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"strictCompatibility":false,"locales":[],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"54.0.1","maxVersion":"54.*"}],"targetPlatforms":[],"multiprocessCompatible":true,"seen":true,"dependencies":[],"hasEmbeddedWebExtension":false,"mpcOptedOut":false,"userPermissions":null}
1500658897569	addons.xpi	DEBUG	Updating XPIState for {"id":"firefox@getpocket.com","syncGUID":"{a020019c-35b3-44bd-a349-a169db904895}","location":"app-system-defaults","version":"1.0.5","type":"extension","internalName":null,"updateURL":null,"updateKey":null,"optionsURL":null,"optionsType":null,"aboutURL":null,"icons":{},"iconURL":null,"icon64URL":null,"defaultLocale":{"name":"Pocket","description":"When you find something you want to view later, put it in Pocket.","creator":null,"homepageURL":null},"visible":true,"active":true,"userDisabled":false,"appDisabled":false,"descriptor":"C:\\Program Files (x86)\\Mozilla Firefox\\browser\\features\\firefox@getpocket.com.xpi","installDate":1495096109000,"updateDate":1500601813802,"applyBackgroundUpdates":1,"bootstrap":true,"skinnable":false,"size":913906,"sourceURI":null,"releaseNotesURI":null,"softDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"strictCompatibility":false,"locales":[],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"54.0.1","maxVersion":"54.*"}],"targetPlatforms":[],"multiprocessCompatible":true,"seen":true,"dependencies":[],"hasEmbeddedWebExtension":false,"mpcOptedOut":false,"userPermissions":null}
1500658897569	addons.xpi	DEBUG	Updating XPIState for {"id":"aushelper@mozilla.org","syncGUID":"{63753757-cc2e-469d-9efc-fa9858c1cdd6}","location":"app-system-defaults","version":"2.0","type":"extension","internalName":null,"updateURL":null,"updateKey":null,"optionsURL":null,"optionsType":null,"aboutURL":null,"icons":{},"iconURL":null,"icon64URL":null,"defaultLocale":{"name":"Application Update Service Helper","description":"Sets value(s) in the update url based on custom checks.","creator":null,"homepageURL":null},"visible":true,"active":true,"userDisabled":false,"appDisabled":false,"descriptor":"C:\\Program Files (x86)\\Mozilla Firefox\\browser\\features\\aushelper@mozilla.org.xpi","installDate":1495096108000,"updateDate":1500601813818,"applyBackgroundUpdates":1,"bootstrap":true,"skinnable":false,"size":8488,"sourceURI":null,"releaseNotesURI":null,"softDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"strictCompatibility":false,"locales":[],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"54.0.1","maxVersion":"54.*"}],"targetPlatforms":[],"multiprocessCompatible":true,"seen":true,"dependencies":[],"hasEmbeddedWebExtension":false,"mpcOptedOut":false,"userPermissions":null}
1500658897570	addons.xpi	DEBUG	Updating XPIState for {"id":"webcompat@mozilla.org","syncGUID":"{a7f6cd4c-1d64-4be2-a29e-5e968645d03f}","location":"app-system-defaults","version":"1.1","type":"extension","internalName":null,"updateURL":null,"updateKey":null,"optionsURL":null,"optionsType":null,"aboutURL":null,"icons":{},"iconURL":null,"icon64URL":null,"defaultLocale":{"name":"Web Compat","description":"Urgent post-release fixes for web compatibility.","creator":null,"homepageURL":null},"visible":true,"active":true,"userDisabled":false,"appDisabled":false,"descriptor":"C:\\Program Files (x86)\\Mozilla Firefox\\browser\\features\\webcompat@mozilla.org.xpi","installDate":1495096108000,"updateDate":1500601813786,"applyBackgroundUpdates":1,"bootstrap":true,"skinnable":false,"size":9006,"sourceURI":null,"releaseNotesURI":null,"softDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"strictCompatibility":false,"locales":[],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"54.0.1","maxVersion":"54.*"}],"targetPlatforms":[],"multiprocessCompatible":true,"seen":true,"dependencies":[],"hasEmbeddedWebExtension":false,"mpcOptedOut":false,"userPermissions":null}
1500658897570	addons.xpi	DEBUG	Updating XPIState for {"id":"screenshots@mozilla.org","syncGUID":"{71ae0579-ac71-4461-90ed-c64ff403066b}","location":"app-system-defaults","version":"6.6.0","type":"extension","internalName":null,"updateURL":null,"updateKey":null,"optionsURL":null,"optionsType":null,"aboutURL":null,"icons":{},"iconURL":null,"icon64URL":null,"defaultLocale":{"name":"Firefox Screenshots","description":null,"creator":null,"homepageURL":"https://pageshot.net/"},"visible":true,"active":true,"userDisabled":false,"appDisabled":false,"descriptor":"C:\\Program Files (x86)\\Mozilla Firefox\\browser\\features\\screenshots@mozilla.org.xpi","installDate":1500601813911,"updateDate":1500601813911,"applyBackgroundUpdates":1,"bootstrap":true,"skinnable":false,"size":716271,"sourceURI":null,"releaseNotesURI":null,"softDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"strictCompatibility":false,"locales":[],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"51.0a1","maxVersion":"*"}],"targetPlatforms":[],"multiprocessCompatible":true,"seen":true,"dependencies":[],"hasEmbeddedWebExtension":false,"mpcOptedOut":false,"userPermissions":null}
1500658897571	addons.xpi	DEBUG	getModTime: Recursive scan of screenshots@mozilla.org
1500658897572	addons.xpi	DEBUG	Updating XPIState for {"id":"{972ce4c6-7e08-4474-a285-3208198ce6fd}","syncGUID":"{d22406cd-8097-4fa9-a7db-412dd3649135}","location":"app-global","version":"54.0.1","type":"theme","internalName":"classic/1.0","updateURL":null,"updateKey":null,"optionsURL":null,"optionsType":null,"aboutURL":null,"icons":{},"iconURL":"chrome://browser/content/default-theme-icon.svg","icon64URL":null,"defaultLocale":{"name":"Default","description":"The default theme.","creator":"Mozilla","homepageURL":null,"contributors":["Mozilla Contributors"]},"visible":true,"active":true,"userDisabled":false,"appDisabled":false,"descriptor":"C:\\Program Files (x86)\\Mozilla Firefox\\browser\\extensions\\{972ce4c6-7e08-4474-a285-3208198ce6fd}.xpi","installDate":1495096108000,"updateDate":1500601813833,"applyBackgroundUpdates":1,"skinnable":true,"size":8207,"sourceURI":null,"releaseNotesURI":null,"softDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"strictCompatibility":true,"locales":[],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"54.0.1","maxVersion":"54.0.1"}],"targetPlatforms":[],"seen":true,"dependencies":[],"hasEmbeddedWebExtension":false,"userPermissions":null}
1500658897573	DeferredSave.extensions.json	DEBUG	Save changes
1500658897575	addons.xpi	DEBUG	Updating database with changes to installed add-ons
1500658897575	addons.xpi-utils	DEBUG	Updating add-on states
1500658897578	addons.xpi-utils	DEBUG	Writing add-ons list
1500658897595	addons.xpi	DEBUG	Registering manifest for C:\Program Files (x86)\Mozilla Firefox\browser\features\aushelper@mozilla.org.xpi
1500658897597	addons.xpi	DEBUG	Calling bootstrap method startup on aushelper@mozilla.org version 2.0
1500658897598	addons.xpi	DEBUG	Registering manifest for C:\Program Files (x86)\Mozilla Firefox\browser\features\e10srollout@mozilla.org.xpi
1500658897599	addons.xpi	DEBUG	Calling bootstrap method startup on e10srollout@mozilla.org version 1.50
1500658897599	addons.xpi	DEBUG	Registering manifest for C:\Program Files (x86)\Mozilla Firefox\browser\features\firefox@getpocket.com.xpi
1500658897600	addons.xpi	DEBUG	Calling bootstrap method startup on firefox@getpocket.com version 1.0.5
1500658897601	addons.xpi	DEBUG	Registering manifest for C:\Program Files (x86)\Mozilla Firefox\browser\features\screenshots@mozilla.org.xpi
1500658897602	addons.xpi	DEBUG	Calling bootstrap method startup on screenshots@mozilla.org version 6.6.0
1500658897603	addons.xpi	DEBUG	Registering manifest for C:\Program Files (x86)\Mozilla Firefox\browser\features\webcompat@mozilla.org.xpi
1500658897605	addons.xpi	DEBUG	Calling bootstrap method startup on webcompat@mozilla.org version 1.1
1500658897618	addons.manager	DEBUG	Registering shutdown blocker for XPIProvider
1500658897618	addons.manager	DEBUG	Provider finished startup: XPIProvider
1500658897618	addons.manager	DEBUG	Starting provider: LightweightThemeManager
1500658897618	addons.manager	DEBUG	Registering shutdown blocker for LightweightThemeManager
1500658897619	addons.manager	DEBUG	Provider finished startup: LightweightThemeManager
1500658897620	addons.manager	DEBUG	Starting provider: GMPProvider
1500658897636	addons.manager	DEBUG	Registering shutdown blocker for GMPProvider
1500658897637	addons.manager	DEBUG	Provider finished startup: GMPProvider
1500658897638	addons.manager	DEBUG	Starting provider: PluginProvider
1500658897638	addons.manager	DEBUG	Registering shutdown blocker for PluginProvider
1500658897639	addons.manager	DEBUG	Provider finished startup: PluginProvider
1500658897640	addons.manager	DEBUG	Completed startup sequence
1500658898087	addons.manager	DEBUG	Starting provider: <unnamed-provider>
1500658898087	addons.manager	DEBUG	Registering shutdown blocker for <unnamed-provider>
1500658898088	addons.manager	DEBUG	Provider finished startup: <unnamed-provider>
1500658898170	addons.manager	DEBUG	Starting provider: PreviousExperimentProvider
1500658898170	addons.manager	DEBUG	Registering shutdown blocker for PreviousExperimentProvider
1500658898171	addons.manager	DEBUG	Provider finished startup: PreviousExperimentProvider
1500658898178	DeferredSave.extensions.json	DEBUG	Starting write
1500658898504	DeferredSave.extensions.json	DEBUG	Write succeeded
1500658898506	addons.xpi-utils	DEBUG	XPI Database saved, setting schema version preference to 19
1500658900480	Marionette	INFO	Listening on port 50303
1500658900926	Marionette	DEBUG	loaded listener.js
Jul 21, 2017 11:11:40 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: W3C
1500658901039	Marionette	DEBUG	Received DOM event "beforeunload" for "about:blank"
[GPU 7244] WARNING: pipe error: 109: file c:/builds/moz2_slave/m-rel-w32-00000000000000000000/build/src/ipc/chromium/src/chrome/common/ipc_channel_win.cc, line 346
Jul 21, 2017 11:11:47 PM org.openqa.selenium.os.UnixProcess destroy
SEVERE: Unable to kill process with PID 2880
Tried to run command without establishing a connection
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: host: 'A1ML18056', ip: '172.18.156.1', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_121'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{moz:profile=C:\Users\M1040326\AppData\Local\Temp\rust_mozprofile.k0GA8zViHeBF, rotatable=false, timeouts={implicit=0.0, pageLoad=300000.0, script=30000.0}, pageLoadStrategy=normal, platform=ANY, specificationLevel=0.0, moz:accessibilityChecks=false, acceptInsecureCerts=false, browserVersion=54.0.1, platformVersion=10.0, moz:processID=3784.0, browserName=firefox, javascriptEnabled=true, platformName=windows_nt}]
Session ID: 82fe5ba0-21fd-4155-8370-d60755d8564e

**Comment by raghavilatha** [comment]
@scottx611x 

My Firefox browser is getting crashed upon firing driver.close().

**Comment by scottx611x** [comment]
@raghavilatha so it looks to me like you are trying to run our tests inside of a Windows host. Our local environment setup takes advantage of the use of Virtualbox and vagrant so that we can ensure a consistent development state regardless of host OS. Our test suite may work on windows host's if all of the dependencies are installed properly, but it's not something we support.

Please follow our instructions to get your local environment setup here: https://github.com/refinery-platform/refinery-platform/blob/develop/README.md#installing-and-launching-for-development

If you run into any trouble after that please feel free to file a [new issue](https://github.com/refinery-platform/refinery-platform/issues/new)

**Pull request merged**
