### PR TITLE
Remove unused templates

### LINKED ISSUE #1993: Remove unused templates
https://github.com/refinery-platform/refinery-platform/issues/783#issuecomment-237878783:
> Also the data set import templates.

Those were not tackled in #1987 and probably still need to be done.

### PR DESCRIPTION
**Pull request by mccalluc**
Fix #1993?

@jkmarx : Looking at this, I think each of these files is still referenced... Do you remember what you meant in saying that the imports could be removed?

### CODE REVIEW

**Comment by jkmarx** [comment]
@mccalluc The isa-tab-import.html template and metadata-table-import.html template were replaced by the angular states (data-set-import/state) The import template is still used as it hooks in the the above states.

Where are these templates being references?

**Comment by mccalluc** [comment]
@jkmarx:

```
$ git grep isa-tab-import.html
refinery/data_set_manager/views.py:    template_name = 'data_set_manager/isa-tab-import.html'
refinery/ui/source/js/data-set-import/directives/isa-tab-import.js:      return $window.getStaticUrl('partials/data-set-import/partials/isa-tab-import.html');
refinery/ui/source/js/data-set-import/state.js:          return window.getStaticUrl('partials/data-set-import/views/isa-tab-import.html');
refinery/ui/source/js/data-set-import/state.spec.js:      mockTemplate(window.getStaticUrl('partials/data-set-import/views/isa-tab-import.html'));

$ git grep metadata-table-import.html
refinery/data_set_manager/views.py:    template_name = 'data_set_manager/metadata-table-import.html'
```

Maybe these referencers are themselves unused? Or they should be?

**Comment by jkmarx** [comment]
$ git grep isa-tab-import.html 
The bottom three refer to the angular partial not the template.

Otherwise, I don't believe those views and templates are being used (recommend you confirm). You can check the current import pages views are the angular partials. I believe Fritz updated them a year or so back.

**Comment by jkmarx** [comment]
```checkFilesUrl: '/data_set_manager/import/check_files/',
      isaTabImportUrl: '/data_set_manager/import/isa-tab-form/',
      tabularFileImportUrl: '/data_set_manager/import/metadata-table-form/',
      uploadUrl: '/data_set_manager/import/chunked-upload/',
      uploadCompleteUrl: '/data_set_manager/import/chunked-upload-complete/',``` Endpoints which are being hit by the current data-set-import

**Comment by mccalluc** [comment]
Replaced by #2059

**Pull request closed without merging**
